# Generated by Django 5.2.8 on 2025-11-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=20)),
                ('distance', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('risk_level', models.PositiveIntegerField()),
                ('previous_instruction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compass.instruction')),
            ],
        ),
    ]
